application: igrubugrub
version: 4
runtime: python
api_version: 1

handlers: 
 - url: /favicon.ico
   static_files: static/img/favicon.ico
   upload: static/imgs/favicon.ico
 - url: /static
   static_dir: static
 - url: /index\.html
   script: app.py 
 - url: .*
   script: app.py
# - url: /.*
#   script: not_found.py 
  